### ISSUE TITLE
Colab bug

### ISSUE THREAD

**Issue by hotfinda** [stevenlsw/physgen#9]
Hi, I tryied to used the colad codes, but there is a bug when I run the following command
%cd diffusion
!python video_diffusion.py --perception_input ../data/$name --previous_output ../outputs/$name

%cd ../
/content/physgen/diffusion
Traceback (most recent call last):
  File "/content/physgen/diffusion/video_diffusion.py", line 15, in <module>
    from diffusers.models import AutoencoderKL
  File "/usr/local/lib/python3.10/dist-packages/diffusers/__init__.py", line 3, in <module>
    from .configuration_utils import ConfigMixin
  File "/usr/local/lib/python3.10/dist-packages/diffusers/configuration_utils.py", line 34, in <module>
    from .utils import (
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/usr/local/lib/python3.10/dist-packages/diffusers/utils/dynamic_modules_utils.py", line 29, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/usr/local/lib/python3.10/dist-packages/huggingface_hub/__init__.py)
/content/physgen

**Comment by stevenlsw** [comment]
Hi, 

Thanks for your interest. This is huggingface upgrade issue. A workable solution is to either remove `cached_download` in your `/usr/local/lib/python3.10/dist-packages/diffusers/utils/dynamic_modules_utils.py` or downgrade by `pip install huggingface_hub==0.25.2`
